GET http://localhost:3000/api/companyuser/authcompanyuser HTTP/1.1
content-type: application/json

{
    "email": "m.bhavsar6@gmail.com",
    "password": "123456"
}

###
GET http://localhost:3000/api/customeruser/authcustomeruser HTTP/1.1
content-type: application/json

{
    "email": "mbh@g.com",
    "password": "123456789"
}

###
POST  http://localhost:3000/api/companyuser/createCompany HTTP/1.1
content-type: application/json

{
    "Fname": "Ami",
    "Lname": "Dave",
    "Email":"amidave80@gmail.com",
    "Password":"ami123",
    "PhoneNumber":"4157891458",
    "CompanyName":"ISI",
    "Website":"www.abc.com",
    "Logo":""
}

###
GET http://localhost:3000/api/customeruser/forgetPasswordCustomer HTTP/1.1
content-type: application/json

{
    "email": "amidave80@gmail.com"
}