POST http://localhost:3000/api/companyuser/authcompanyuser HTTP/1.1
content-type: application/json

{
    "email": "m.bh@gmail.com",
    "password": "123456"
}

###
POST http://localhost:3000/api/customeruser/authcustomeruser HTTP/1.1
content-type: application/json

{
    "email": "mpbh@gmail.com",
    "password": "123"
}

// For Creating Company User and Company Details ---------------->

###
POST  http://localhost:3000/api/companyuser/createCompany HTTP/1.1
content-type: application/json

{   
    "Fname": "Ami",
    "Lname": "Dave",
    "Email":"amidav11e80@gmail.com",
    "Password":"ami123",
    "PhoneNumber":"4157891458",
    "CompanyName":"IS11I",
    "Website":"www.abc.com",
    "Logo":"‪D:\SuperMarket-Project\logo.jpeg",
    "Address1":"12,4000",
    "Address2":"Rue Barclay",
    "City":"Montreal",
    "CountryId":"1",
    "ProvinceId":"1",
    "PostalCode":"H3S1K3"
}
// Forget Password for Company User -------------------------->
###

POST http://localhost:3000/api/companyuser/forgetPasswordCompany HTTP/1.1
content-type: application/json

{
    "email": "amidave80@gmail.com"
}
//creating new customer on app
###
POST   http://localhost:3000/api/customeruser/createcustomeruser HTTP/1.1
content-type: application/json

{
        "Fname": "Loveleen",
        "Lname": "minhas",
        "email":"minh8as@gmail.com",
        "phonenumber":"1234567898",
        "countryid":1,
        "provinceid":2,
        "city":"montreal",
        "postal":"asdff",
        "address":"bvjdnks",
        "password":"lovellen1234",
        "companyid":1  
}


// Forget Password for Customer User ----------------------->
###
GET http://localhost:3000/api/customeruser/forgetPasswordCustomer HTTP/1.1
content-type: application/json

{
    "email": "minhasloveleen@gmail.com"
}

// creating New Supplier ----------------------------------> 
###

POST  http://localhost:3000/api/supplier/createSupplier HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFtaTE0M0BnbWFpbC5jb20iLCJpYXQiOjE1ODQ5MTk4OTB9.SxQ4AjeIVZEXNwUcd8UH0xAghCtjD0wJfQfwfZUuG68
content-type: application/json

{
    "SupplierName" :"Meh33kkul1 B1havsar",
    "SupplierEmail": "suppliuu321er119@gom",
    "SupplierPhone":"4157891458",
    "DiscountRate":"10",
    "CountryId":"1",
    "ProvinceId":"1",
    "Address1":"3,3225",
    "Address2":"Rue Saint Denis",
    "City":"Montreal",
    "PostalCode":"H3S1J3",
    "CompanyId" : "1"
}

###
//Edit Supplier deatils --------------------->
PUT  http://localhost:3000/api/supplier/editsupplier HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFtaTE0M0BnbWFpbC5jb20iLCJpYXQiOjE1ODQ5MTk4OTB9.SxQ4AjeIVZEXNwUcd8UH0xAghCtjD0wJfQfwfZUuG68

{
    "SupplierId"  : "4",
    "SupplierName": "Ahm corp",
    "SupplierEmail": "amhcorp@gmail.com",
    "SupplierPhone":"4157891458",
    "DiscountRate":"15",
    "CountryId":"1",
    "ProvinceId":"1",
    "Address1":"500",
    "Address2":"Rue Sherbrook",
    "City":"Montreal",
    "PostalCode":"H4R8H3",
    "CompanyId" : "1"
}

// Get Supplier By Id ------------------------->
###

GET http://localhost:3000/api/supplier/getsupplierbyId?SupplierId=9&CompanyId=1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFtaTE0M0BnbWFpbC5jb20iLCJpYXQiOjE1ODQ5MTk4OTB9.SxQ4AjeIVZEXNwUcd8UH0xAghCtjD0wJfQfwfZUuG68
content-type: application/json


###

POST http://localhost:3000/api/supplier/getsuppliers HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFtaTE0M0BnbWFpbC5jb20iLCJpYXQiOjE1ODQ5MTk4OTB9.SxQ4AjeIVZEXNwUcd8UH0xAghCtjD0wJfQfwfZUuG68
content-type: application/json

{
   "CompanyId":50
}

####
Query Param
//SupplierName
//SupplierId
//City
//CountryName
//



//fetching countries
###
GET http://localhost:3000/api/countries/country HTTP/1.1
content-type: application/json


//for fetching provinces by passing country id
###
POST http://localhost:3000/api/provinces/province HTTP/1.1
content-type: application/json

{
    "country_id": 150
}

// Add new Product -------------------------------->
###

POST  http://localhost:3000/api/product/createproduct HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFtaTE0M0BnbWFpbC5jb20iLCJpYXQiOjE1ODQ5MTk4OTB9.SxQ4AjeIVZEXNwUcd8UH0xAghCtjD0wJfQfwfZUuG68
content-type: application/json

{
    "Product_name":"V-neck Dress",
    "SKU":"clh-1000-01",
    "PurchasePrice":"50",
    "RetailPrice":"55",
    "CategoryId":2,
    "Country_Origin_id":1,
    "Image":"‪D:\\SuperMarket-Project\\logo.jpeg",
    "SupplierId":2,
    "Barcode":"45000 10000",
    "Qty_minimum_required":50,
    "CompanyId":1
}
//creating new  category
###
POST http://localhost:3000/api/category/createCategory HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFtaTE0M0BnbWFpbC5jb20iLCJpYXQiOjE1ODQ5MTk4OTB9.SxQ4AjeIVZEXNwUcd8UH0xAghCtjD0wJfQfwfZUuG68
content-type: application/json

{
    "categoryname": "Bags",
    "SKU": "bgs-1000-01",
    "tags": "sports",
    "companyid":1
}

// Edit category ------------------------------------->

###
PUT  http://localhost:3000/api/category/editcategory HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFtaTE0M0BnbWFpbC5jb20iLCJpYXQiOjE1ODQ5MTk4OTB9.SxQ4AjeIVZEXNwUcd8UH0xAghCtjD0wJfQfwfZUuG68
content-type: application/json

{
    "categoryId": "5",
    "categoryname":"Jackets",
    "SKU": "jns-1000-01",
    "tags"  : "Winter"
}

// Get all Categories ------------------------------->
###
POST  http://localhost:3000/api/category/getcategories HTTP/1.1
content-type: application/json

{
    "CompanyId": 1
}

// Get category By Id ----------------------->
###

GET http://localhost:3000/api/category/getcategorybyId?CategoryId=1001&CompanyId=1 HTTP/1.1
content-type: application/json




// Delete Product ------------------------------>
### 

PUT http://localhost:3000/api/product/deleteproduct HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFtaTE0M0BnbWFpbC5jb20iLCJpYXQiOjE1ODQ5MTk4OTB9.SxQ4AjeIVZEXNwUcd8UH0xAghCtjD0wJfQfwfZUuG68
content-type: application/json

{
    "ProductId":"8"
}

// Edit Product --------------------------------------->
###

PUT  http://localhost:3000/api/product/editproduct HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFtaTE0M0BnbWFpbC5jb20iLCJpYXQiOjE1ODQ5MTk4OTB9.SxQ4AjeIVZEXNwUcd8UH0xAghCtjD0wJfQfwfZUuG68

{
    "ProductId":8,
    "ProductName":"Mesh Sneakers",
    "Description":"Sneakers in mesh, faux leather",
    "PurchasePrice":"120",
    "RetailPrice":"150",
    "CategoryId":1,
    "Country_Origin_id":1,
    "Image":"‪D:\\SuperMarket-Project\\logo.jpeg",
    "SupplierId":1,
    "QtyMinRequired":20,
    "CompanyId":1
}

// Get All Products ----------------------------> 
###
POST  http://localhost:3000/api/product/getproducts HTTP/1.1
content-type: application/json

{
    "CompanyId": 1
}

// Get Product By Id ---------------------------->
###

GET http://localhost:3000/api/product/getproductbyId?ProductId=5&CompanyId=1 HTTP/1.1
content-type: application/json

// Get Suppiler By Id ---------------------------->
###

GET http://localhost:3000/api/supplier/getsupplierbyId?SupplierId=10&CompanyId=1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFtaTE0M0BnbWFpbC5jb20iLCJpYXQiOjE1ODQ5MTk4OTB9.SxQ4AjeIVZEXNwUcd8UH0xAghCtjD0wJfQfwfZUuG68
content-type: application/json

// Create Puchase Order -------------------------------------------->
###
POST  http://localhost:3000/api/purchaseorder/create HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFtaTE0M0BnbWFpbC5jb20iLCJpYXQiOjE1ODQ5MTk4OTB9.SxQ4AjeIVZEXNwUcd8UH0xAghCtjD0wJfQfwfZUuG68
content-type: application/json

{
    "SupplierId":20,
    "CurrencyId":1,
    "DiscountRate":10,
    "PurchaseOrderTotal":1000,
    "products":[
         {
           "ProductId":5,
           "Price": 180,
           "Quantity":50,
           "Total":6000
        },
        {
           "ProductId":6,
           "Price": 190,
           "Quantity":100,
           "Total":17000 
        }
    ]
}
//create sales api
###
POST http://localhost:3000/api/sales/createsales HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFtaTE0M0BnbWFpbC5jb20iLCJpYXQiOjE1ODQ5MTk4OTB9.SxQ4AjeIVZEXNwUcd8UH0xAghCtjD0wJfQfwfZUuG68
content-type: application/json

{
    "customerid":"1",
    "total":"15000",
    "product": [{"productid": "1",
                  "qty" : "2",
                  "price": "12.33",
                  "subtotal":"10000"},
                  {"productid": "2",
                  "qty" : "2",
                  "price": "166.33",
                  "subtotal":"5000"}]
}
// Edit Purchase Order -------------------------------->

###
PUT  http://localhost:3000/api/purchaseorder/edit HTTP/1.1
content-type: application/json

{
    "purchase_ord_id":3,
    "SupplierId":1,
    "PurchaseOrderTotal":10000,
    "products":[
        {
           "PurchaseOrder_ProductId":2,
           "Quantity":40,
           "Total":3000 
        },
        {
           "PurchaseOrder_ProductId":5,
           "Quantity":15,
           "Total":10000 
        }
    ]
}

POST  http://localhost:3000/api/delivery/create HTTP/1.1
content-type: application/json

{
    "PurchaseOrderId":"4"
}

####


########
// get All delivery 
//Search Query param
//SupplierName
//DeliveryId
//Status 
###

####

POST  http://localhost:3000/api/delivery/getdeliveries HTTP/1.1
content-type: application/json

{
    "CompanyId":"4"
}

// Cancel Purchase Order ------------------------------>
### 

PUT http://localhost:3000/api/purchaseorder/cancel HTTP/1.1
content-type: application/json

{
    "Purchase_OrderId":2
}

// Get all Purchase orders  ------------------------------->
###
POST  http://localhost:3000/api/purchaseorder/getpurchaseorders HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im0uYmhAZ21haWwuY29tIiwiaWF0IjoxNTg1MTQ1NzU1fQ.o2x53pTPmGEEp9you24Iqgz5HyIhJ_oM9rH-RUPZ-0s
content-type: application/json

{
    "CompanyId":2
}



//fetch the most popular product
###
GET http://localhost:3000/api/product/featureproduct HTTP/1.1
content-type: application/json

//edit user customer 
###
POST   http://localhost:3000/api/customeruser/editcustomeruser HTTP/1.1
content-type: application/json

{
    "id":"1",
    "Fname": "loveleen11",
    "Lname": "minhas",
    "email":"minhas@gmail.com",
    "phonenumber":"1234567898",
    "countryid":1,
    "provinceid":2,
    "city":"jalan",
    "postal":"asdff",
    "address":"bvjdnks",
    "password":"123",
    "companyid":1  
}

// Get Sales By Id 
###

GET http://localhost:3000/api/sales/getsalesorderbyid?orderid=50&companyid=1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFtaTE0M0BnbWFpbC5jb20iLCJpYXQiOjE1ODQ5MTk4OTB9.SxQ4AjeIVZEXNwUcd8UH0xAghCtjD0wJfQfwfZUuG68
content-type: application/json

// Get sales---by filter---------------------->
###
POST http://localhost:3000/api/sales/getsales?CustomerOrderId=1&Date=2020-03-24 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFtaTE0M0BnbWFpbC5jb20iLCJpYXQiOjE1ODQ5MTk4OTB9.SxQ4AjeIVZEXNwUcd8UH0xAghCtjD0wJfQfwfZUuG68
content-type: application/json

{
    "companyid":"1"
}
// Get all sales----------------------->
###
POST http://localhost:3000/api/sales/getsales HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFtaTE0M0BnbWFpbC5jb20iLCJpYXQiOjE1ODQ5MTk4OTB9.SxQ4AjeIVZEXNwUcd8UH0xAghCtjD0wJfQfwfZUuG68
content-type: application/json

{
    "companyid":"1"
}
