GET http://localhost:3000/api/companyuser/authcompanyuser HTTP/1.1

content-type: application/json

{
    "email": "m.bhavsar6@gmail.com",
    "password": "123456"
}

###
GET http://localhost:3000/api/customeruser/authcustomeruser HTTP/1.1
content-type: application/json

{
    "email": "mbh@g.com",
    "password": "123456789"
}

###
POST  http://localhost:3000/api/companyuser/createCompany HTTP/1.1
content-type: application/json

{
    "Fname": "Ami",
    "Lname": "Dave",
    "Email":"amidave800@gmail.com",
    "Password":"ami123",
    "PhoneNumber":"4157891458",
    "CompanyName":"ISII",
    "Website":"www.abc.com",
    "Logo":"‪D:\\SuperMarket-Project\\logo.jpeg",
    "Address1":"12,4000",
    "Address2":"Rue Barclay",
    "City":"Montreal",
    "CountryId":"1",
    "ProvinceId":"1",
    "PostalCode":"H3S1K3",

}

###

POST   http://localhost:3000/api/customeruser/createcustomeruser HTTP/1.1
content-type: application/json

{
    "fname": "loveleen",
        "lname": "minhas",
        "email":"minhaslovelesenbsjdh@gmail.com",
        "phonenumber":"1234567898",
        "countryid":1,
        "provinceid":2,
        "city":"jalan",
        "postal":"asdff",
        "address":"bvjdnks",
        "password":"123",
        "companyid":1  
    }

###
GET http://localhost:3000/api/customeruser/forgetPasswordCustomer HTTP/1.1
content-type: application/json

{
    "email": "amidave80@gmail.com"
}

###
GET http://localhost:3000/api/countries/g HTTP/1.1
content-type: application/json

###
POST http://localhost:3000/api/countries/g HTTP/1.1
content-type: application/json






